#!/usr/bin/env python3
"""Generate human-readable Markdown from the canonical CSV files."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from catalog_lib import ROOT, account_links, all_rows, counts, link, load_catalog, md, split_tags


TIER_ORDER = {"A": 0, "B": 1, "C": 2, "D": 3, "Reference": 4}
TITLES = {
    "organizations": "Organizations",
    "people": "Researchers and leaders",
    "media": "Media and education",
    "resources": "Scientific resources",
}


def row_key(row: dict[str, str]) -> tuple[int, str]:
    return TIER_ORDER.get(row["tier"], 99), row["name"].casefold()


def inferred_people_category(row: dict[str, str]) -> str:
    tags = set(split_tags(row["focus"]))
    rules = [
        ({"ai-safety", "alignment", "interpretability"}, "AI safety and interpretability"),
        ({"ai-ethics", "responsible-ai", "ai-policy"}, "Responsible AI and policy"),
        ({"robotics", "autonomous-systems", "reinforcement-learning"}, "Robotics and reinforcement learning"),
        ({"computational-biology", "healthcare", "ai-for-science", "scientific-ml"}, "AI for science and health"),
        ({"computer-vision", "image-generation", "generative-ai"}, "Vision and generative models"),
        ({"nlp", "speech", "foundation-models"}, "Language and foundation models"),
        ({"ml-systems", "hardware", "distributed-computing"}, "ML systems and infrastructure"),
        ({"ml-theory", "probabilistic-ml", "causal-inference"}, "Machine learning foundations"),
    ]
    for matching_tags, category in rules:
        if tags & matching_tags:
            return category
    return "Other AI research"


def build_catalog(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    lines = [
        "# Awesome Global AI Catalog",
        "",
        f"> {total} curated entries. Generated from `data/*.csv`; do not edit this file manually.",
        "",
        "Tiers are discovery aids rather than a strict ranking. See [Methodology](docs/METHODOLOGY.md).",
        "",
    ]
    for entity_type, rows in catalog.items():
        lines.extend([f"## {TITLES[entity_type]}", ""])
        grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
        for row in rows:
            category = row.get("category") or (inferred_people_category(row) if entity_type == "people" else "Other")
            grouped[category].append(row)
        for category in sorted(grouped):
            lines.extend([f"### {md(category)}", ""])
            if entity_type == "people":
                lines.extend(["| Name | Affiliation | Country | Focus | Tier | Accounts |", "|---|---|---|---|:---:|---|"])
                for row in sorted(grouped[category], key=row_key):
                    lines.append(
                        f"| {link(row['name'], row['website'])} | {md(row.get('affiliation', ''))} | "
                        f"{md(row['country'])} | {md(', '.join(split_tags(row['focus'])))} | "
                        f"{row['tier']} | {account_links(row)} |"
                    )
            else:
                lines.extend(["| Name | Country | Focus | Tier | Accounts |", "|---|---|---|:---:|---|"])
                for row in sorted(grouped[category], key=row_key):
                    lines.append(
                        f"| {link(row['name'], row['website'])} | {md(row['country'])} | "
                        f"{md(', '.join(split_tags(row['focus'])))} | {row['tier']} | {account_links(row)} |"
                    )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def counter_table(title: str, counter, limit: int | None = None) -> list[str]:
    rows = counter.most_common(limit)
    return [f"## {title}", "", "| Value | Entries |", "|---|---:|"] + [
        f"| {md(value)} | {count} |" for value, count in rows
    ] + [""]


def build_stats(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    data = counts(catalog)
    lines = ["# Catalog statistics", "", f"Generated catalog size: **{total} entries**.", "", "## Entity types", "", "| Type | Entries |", "|---|---:|"]
    lines.extend(f"| {TITLES[kind]} | {len(rows)} |" for kind, rows in catalog.items())
    lines.append("")
    lines.extend(counter_table("Tiers", data["tiers"]))
    lines.extend(counter_table("Regions", data["regions"]))
    lines.extend(counter_table("Countries and scopes", data["countries"]))
    lines.extend(counter_table("Most represented focus tags", data["focus"], 40))
    return "\n".join(lines).rstrip() + "\n"


def build_readme(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    orgs = len(catalog["organizations"])
    people = len(catalog["people"])
    media = len(catalog["media"])
    resources = len(catalog["resources"])
    return f"""# Awesome Global AI

A verified and structured directory of leading AI organizations, researchers, scientific resources, media, and official social accounts from around the world.

**{total} entries:** {orgs} organizations · {people} people · {media} media sources · {resources} scientific resources.

> Snapshot verified on 2026-10-04. This is a curated discovery directory rather than a definitive ranking.

## Browse

- **[Full catalog](CATALOG.md)** — organizations, people, media, conferences, journals, benchmarks, and databases.
- **[Statistics](docs/STATS.md)** — coverage by entity type, region, country, tier, and focus.
- **[Methodology](docs/METHODOLOGY.md)** — inclusion, tiers, verification, and maintenance.
- **[Sources](docs/SOURCES.md)** and **[editorial notes](docs/EDITORIAL_NOTES.md)** — discovery inputs and snapshot limitations.
- **[Русская справка](docs/README.ru.md)**.
- **[Canonical data](data/)** — reusable CSV files and a generated combined JSON export.

## Scope

The directory includes frontier model labs, Big Tech research teams, universities, independent institutes, open-source communities, AI infrastructure, robotics, AI for science, safety and governance organizations, researchers, YouTube channels, podcasts, newsletters, conferences, journals, paper discovery tools, model hubs, datasets, and benchmarks.

Each entry separates its **entity type** from its **focus tags**, making the data useful for both people and software. Social links are attached to their owning entity instead of being duplicated as standalone recommendations.

## Quality model

- **A:** global leader or field-defining contributor.
- **B:** major international or regional contributor.
- **C:** authoritative specialist.
- **D:** emerging project tracked for breadth.
- **Reference:** infrastructure for research discovery that should not be ranked competitively.

Every accepted entry has an official or primary verification URL and a verification date. Unresolved suggestions go to `data/candidates.csv`.

## Validate and regenerate

```bash
python3 scripts/validate_catalog.py
python3 scripts/generate_catalog.py
```

Optional live website probe:

```bash
python3 scripts/validate_catalog.py --check-links
```

## Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md). Contributions should add primary sources and avoid promotional language. The catalog data is available under [CC BY 4.0](LICENSE).
"""


def main() -> None:
    catalog = load_catalog()
    (ROOT / "CATALOG.md").write_text(build_catalog(catalog), encoding="utf-8")
    (ROOT / "docs" / "STATS.md").write_text(build_stats(catalog), encoding="utf-8")
    (ROOT / "README.md").write_text(build_readme(catalog), encoding="utf-8")
    combined = [dict(row, entity_type=entity_type) for entity_type, row in all_rows(catalog)]
    (ROOT / "data" / "catalog.json").write_text(
        json.dumps(combined, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    total = sum(len(rows) for rows in catalog.values())
    print(f"Generated Markdown and data/catalog.json from {total} entries.")


if __name__ == "__main__":
    main()
