#!/usr/bin/env python3
"""Generate human-readable Markdown from the canonical CSV files."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from catalog_lib import ROOT, account_links, all_rows, counts, link, load_catalog, md, split_tags


TIER_ORDER = {"A": 0, "B": 1, "C": 2, "D": 3, "Reference": 4}
TITLES = {
    "organizations": "Organizations",
    "people": "Researchers and leaders",
    "media": "Media and education",
    "resources": "Scientific resources",
}

README_SECTIONS = {
    "organizations": {
        "title": "Organizations",
        "intro": (
            "Frontier labs, university centers, open-source communities, infrastructure "
            "providers, robotics teams, policy groups, and specialized AI companies."
        ),
    },
    "people": {
        "title": "Researchers and leaders",
        "intro": (
            "Researchers, engineers, founders, and policy leaders whose work has shaped "
            "modern artificial intelligence."
        ),
    },
    "media": {
        "title": "Media and education",
        "intro": (
            "Technical YouTube channels, podcasts, newsletters, courses, and research "
            "explainers for following and learning AI."
        ),
    },
    "resources": {
        "title": "Scientific resources",
        "intro": (
            "Paper indexes, model and dataset hubs, benchmarks, conferences, journals, "
            "and other infrastructure for serious research."
        ),
    },
}

ACCOUNT_LABELS = [
    ("GitHub", "github"),
    ("YouTube", "youtube"),
    ("X", "x"),
    ("LinkedIn", "linkedin"),
    ("Hugging Face", "huggingface"),
    ("Scholar", "scholar"),
]


def row_key(row: dict[str, str]) -> tuple[int, str]:
    return TIER_ORDER.get(row["tier"], 99), row["name"].casefold()


def inferred_people_category(row: dict[str, str]) -> str:
    tags = set(split_tags(row["focus"]))
    rules = [
        ({"ai-safety", "alignment", "interpretability"}, "AI safety and interpretability"),
        ({"ai-ethics", "responsible-ai", "ai-policy"}, "Responsible AI and policy"),
        ({"robotics", "autonomous-systems", "reinforcement-learning"}, "Robotics and reinforcement learning"),
        ({"computational-biology", "healthcare", "ai-for-science", "scientific-ml"}, "AI for science and health"),
        ({"computer-vision", "image-generation", "generative-ai"}, "Vision and generative models"),
        ({"nlp", "speech", "foundation-models"}, "Language and foundation models"),
        ({"ml-systems", "hardware", "distributed-computing"}, "ML systems and infrastructure"),
        ({"ml-theory", "probabilistic-ml", "causal-inference"}, "Machine learning foundations"),
    ]
    for matching_tags, category in rules:
        if tags & matching_tags:
            return category
    return "Other AI research"


def display_kind(value: str) -> str:
    acronyms = {"ai": "AI", "ml": "ML", "nlp": "NLP"}
    return " ".join(
        acronyms.get(word, word.title()) for word in value.replace("-", " ").split()
    )


def readme_account_links(row: dict[str, str]) -> str:
    return " · ".join(
        f"[{label}]({row[field]})"
        for label, field in ACCOUNT_LABELS
        if row.get(field)
    )


def readme_metadata(row: dict[str, str], entity_type: str) -> str:
    items = [md(row["country"])]
    if entity_type == "people" and row.get("affiliation"):
        items.append(md(row["affiliation"]))
    if entity_type == "media" and row.get("language"):
        items.append(md(row["language"]))
    if row.get("kind"):
        items.append(md(display_kind(row["kind"])))
    tier = row["tier"]
    items.append("Reference" if tier == "Reference" else f"Tier {tier}")
    return " · ".join(items)


def readme_entry(row: dict[str, str], entity_type: str) -> list[str]:
    topics = " · ".join(f"`{md(tag)}`" for tag in split_tags(row["focus"]))
    lines = [
        f"- **{link(row['name'], row['website'])}** — {md(row['description'])}  ",
        f"  {readme_metadata(row, entity_type)}  ",
    ]
    accounts = readme_account_links(row)
    if accounts:
        lines.append(f"  {accounts}  ")
    lines.extend([f"  Topics: {topics}", ""])
    return lines


def grouped_rows(
    rows: list[dict[str, str]], entity_type: str
) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        category = row.get("category") or (
            inferred_people_category(row) if entity_type == "people" else "Other"
        )
        grouped[category].append(row)
    return grouped


def build_catalog(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    lines = [
        "# Awesome Global AI Catalog",
        "",
        f"> {total} curated entries. Generated from `data/*.csv`; do not edit this file manually.",
        "",
        "Tiers are discovery aids rather than a strict ranking. See [Methodology](docs/METHODOLOGY.md).",
        "",
    ]
    for entity_type, rows in catalog.items():
        lines.extend([f"## {TITLES[entity_type]}", ""])
        grouped = grouped_rows(rows, entity_type)
        for category in sorted(grouped):
            lines.extend([f"### {md(category)}", ""])
            if entity_type == "people":
                lines.extend(["| Name | Affiliation | Country | Focus | Tier | Accounts |", "|---|---|---|---|:---:|---|"])
                for row in sorted(grouped[category], key=row_key):
                    lines.append(
                        f"| {link(row['name'], row['website'])} | {md(row.get('affiliation', ''))} | "
                        f"{md(row['country'])} | {md(', '.join(split_tags(row['focus'])))} | "
                        f"{row['tier']} | {account_links(row)} |"
                    )
            else:
                lines.extend(["| Name | Country | Focus | Tier | Accounts |", "|---|---|---|:---:|---|"])
                for row in sorted(grouped[category], key=row_key):
                    lines.append(
                        f"| {link(row['name'], row['website'])} | {md(row['country'])} | "
                        f"{md(', '.join(split_tags(row['focus'])))} | {row['tier']} | {account_links(row)} |"
                    )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def counter_table(title: str, counter, limit: int | None = None) -> list[str]:
    rows = counter.most_common(limit)
    return [f"## {title}", "", "| Value | Entries |", "|---|---:|"] + [
        f"| {md(value)} | {count} |" for value, count in rows
    ] + [""]


def build_stats(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    data = counts(catalog)
    lines = ["# Catalog statistics", "", f"Generated catalog size: **{total} entries**.", "", "## Entity types", "", "| Type | Entries |", "|---|---:|"]
    lines.extend(f"| {TITLES[kind]} | {len(rows)} |" for kind, rows in catalog.items())
    lines.append("")
    lines.extend(counter_table("Tiers", data["tiers"]))
    lines.extend(counter_table("Regions", data["regions"]))
    lines.extend(counter_table("Countries and scopes", data["countries"]))
    lines.extend(counter_table("Most represented focus tags", data["focus"], 40))
    return "\n".join(lines).rstrip() + "\n"


def build_readme(catalog: dict[str, list[dict[str, str]]]) -> str:
    total = sum(len(rows) for rows in catalog.values())
    orgs = len(catalog["organizations"])
    people = len(catalog["people"])
    media = len(catalog["media"])
    resources = len(catalog["resources"])
    snapshot_date = max(
        row["verified_at"] for _, row in all_rows(catalog) if row.get("verified_at")
    )
    lines = [
        "# Awesome Global AI",
        "",
        "A verified, structured, and browsable directory of leading AI organizations, "
        "researchers, scientific resources, media, and official social accounts from around the world.",
        "",
        f"**{total} entries:** {orgs} organizations · {people} people · "
        f"{media} media sources · {resources} scientific resources.",
        "",
        f"> Snapshot verified on {snapshot_date}. This is a curated discovery directory, "
        "not a definitive ranking.",
        "",
        "## Explore the catalog",
        "",
        f"- [Organizations — {orgs}](#organizations)",
        f"- [Researchers and leaders — {people}](#researchers-and-leaders)",
        f"- [Media and education — {media}](#media-and-education)",
        f"- [Scientific resources — {resources}](#scientific-resources)",
        "",
        "Each name opens the primary website. Additional links lead directly to official "
        "profiles on GitHub, YouTube, X, LinkedIn, Hugging Face, or Google Scholar. "
        "Topic tags make narrow specialties easy to scan.",
        "",
        "**Tier guide:** **A** — field-defining · **B** — major contributor · "
        "**C** — authoritative specialist · **D** — emerging project · "
        "**Reference** — research infrastructure that is not ranked competitively.",
        "",
        "---",
        "",
    ]

    anchors = {
        "organizations": "organizations",
        "people": "researchers-and-leaders",
        "media": "media-and-education",
        "resources": "scientific-resources",
    }
    for entity_type, rows in catalog.items():
        section = README_SECTIONS[entity_type]
        lines.extend(
            [
                f'<a id="{anchors[entity_type]}"></a>',
                "",
                f"## {section['title']}",
                "",
                f"{section['intro']} **{len(rows)} entries.**",
                "",
            ]
        )
        grouped = grouped_rows(rows, entity_type)
        for category in sorted(grouped):
            category_rows = sorted(grouped[category], key=row_key)
            lines.extend([f"### {md(category)} ({len(category_rows)})", ""])
            for row in category_rows:
                lines.extend(readme_entry(row, entity_type))
        lines.extend(["[Back to catalog navigation](#explore-the-catalog)", "", "---", ""])

    lines.extend(
        [
            "## Data, methodology, and contributing",
            "",
            "The README is generated from the canonical CSV files, so the human-readable "
            "directory and reusable data stay synchronized.",
            "",
            "- [CSV and combined JSON data](data/)",
            "- [Alternative table view](CATALOG.md)",
            "- [Coverage statistics](docs/STATS.md)",
            "- [Selection and verification methodology](docs/METHODOLOGY.md)",
            "- [Discovery sources](docs/SOURCES.md) and "
            "[editorial notes](docs/EDITORIAL_NOTES.md)",
            "- [Русская справка](docs/README.ru.md)",
            "",
            "Every accepted entry has an official or primary verification URL and a "
            "verification date. Unresolved suggestions go to `data/candidates.csv`.",
            "",
            "### Validate and regenerate",
            "",
            "```bash",
            "python3 scripts/validate_catalog.py",
            "python3 scripts/generate_catalog.py",
            "```",
            "",
            "For an optional live website probe, run "
            "`python3 scripts/validate_catalog.py --check-links`.",
            "",
            "### Contributing",
            "",
            "See [CONTRIBUTING.md](CONTRIBUTING.md). Contributions should add primary "
            "sources and avoid promotional language. The catalog data is available under "
            "[CC BY 4.0](LICENSE).",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    catalog = load_catalog()
    (ROOT / "CATALOG.md").write_text(build_catalog(catalog), encoding="utf-8")
    (ROOT / "docs" / "STATS.md").write_text(build_stats(catalog), encoding="utf-8")
    (ROOT / "README.md").write_text(build_readme(catalog), encoding="utf-8")
    combined = [dict(row, entity_type=entity_type) for entity_type, row in all_rows(catalog)]
    (ROOT / "data" / "catalog.json").write_text(
        json.dumps(combined, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    total = sum(len(rows) for rows in catalog.values())
    print(f"Generated Markdown and data/catalog.json from {total} entries.")


if __name__ == "__main__":
    main()
